<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/01/12 12:22:48
return array(

  // pmModelUtilsPlugin_module_libs

  // pmModelUtilsPlugin_lib
  'basemeta' => '/Users/patriciomacadden/Desarrollo/testing2/plugins/pmModelUtilsPlugin/lib/BaseMeta.class.php',
  'pmvalidatormetachoice' => '/Users/patriciomacadden/Desarrollo/testing2/plugins/pmModelUtilsPlugin/lib/validator/pmValidatorMetaChoice.class.php',
  'pmwidgetformmetachoice' => '/Users/patriciomacadden/Desarrollo/testing2/plugins/pmModelUtilsPlugin/lib/widget/pmWidgetFormMetaChoice.php',

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfmixer' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformfiltergenerator' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelgenerateadmintask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoxmltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sftesterpropel' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfwidgetformpropelchoice' => '/Developer/Library/Frameworks/Symfony/1.4/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',

  // project
  'articleformfilter' => '/Users/patriciomacadden/Desarrollo/testing2/lib/filter/ArticleFormFilter.class.php',
  'basearticleformfilter' => '/Users/patriciomacadden/Desarrollo/testing2/lib/filter/base/BaseArticleFormFilter.class.php',
  'baseformfilterpropel' => '/Users/patriciomacadden/Desarrollo/testing2/lib/filter/BaseFormFilterPropel.class.php',
  'articleform' => '/Users/patriciomacadden/Desarrollo/testing2/lib/form/ArticleForm.class.php',
  'basearticleform' => '/Users/patriciomacadden/Desarrollo/testing2/lib/form/base/BaseArticleForm.class.php',
  'baseform' => '/Users/patriciomacadden/Desarrollo/testing2/lib/form/BaseForm.class.php',
  'baseformpropel' => '/Users/patriciomacadden/Desarrollo/testing2/lib/form/BaseFormPropel.class.php',
  'articlestatus' => '/Users/patriciomacadden/Desarrollo/testing2/lib/meta/ArticleStatus.class.php',

  // project_model
  'article' => '/Users/patriciomacadden/Desarrollo/testing2/lib/model/Article.php',
  'articlepeer' => '/Users/patriciomacadden/Desarrollo/testing2/lib/model/ArticlePeer.php',
  'articletablemap' => '/Users/patriciomacadden/Desarrollo/testing2/lib/model/map/ArticleTableMap.php',
  'basearticle' => '/Users/patriciomacadden/Desarrollo/testing2/lib/model/om/BaseArticle.php',
  'basearticlepeer' => '/Users/patriciomacadden/Desarrollo/testing2/lib/model/om/BaseArticlePeer.php',

  // application
  'myuser' => '/Users/patriciomacadden/Desarrollo/testing2/apps/frontend/lib/myUser.class.php',

  // modules
  'article/articlegeneratorconfiguration' => '/Users/patriciomacadden/Desarrollo/testing2/apps/frontend/modules/article/lib/articleGeneratorConfiguration.class.php',
  'article/articlegeneratorhelper' => '/Users/patriciomacadden/Desarrollo/testing2/apps/frontend/modules/article/lib/articleGeneratorHelper.class.php',
);
